name: Feature request
description: Propose a new idea.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using Syncfusion widgets!

        If you are looking for support, please check out our documentation, knowledge base, 
        and feedbacks. If you are unable to find a solution, please report the bug here.

          - [User Guide Documentation](https://help.syncfusion.com/flutter/introduction/overview)
          - [Knowledge Base](https://support.syncfusion.com/kb/cross-platforms/category/79)
          - [Feedbacks](https://stackoverflow.com/questions/tagged/flutter?sort=frequent)
          
        You can also contact us through the following methods.
          - [Support portal](https://support.syncfusion.com)
          - [Support forums](https://www.syncfusion.com/forums)
          - [Feedback portal](https://www.syncfusion.com/feedback/flutter)
  - type: textarea
    attributes:
      label: Use case
      description: |
        Kindly inform us of the issue you're encountering which has prompted you to suggest a new feature.
        If your proposed feature is based on an existing problem, 
        could you please provide a detailed and concise explanation of the issue?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: |
        Please provide a concise and precise description of your proposal.

        Include a visual representation of your concept.
         * code samples
         * images (illustrations, diagrams, screenshots)
         * videos
    validations:
      required: true