name: syncfusion_flutter_core
description: Syncfusion Flutter Core is a dependent package for all the Syncfusion Flutter widgets. 
version: 30.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  vector_math: ">=2.1.0 <=4.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
